### ISSUE TITLE
Suggestion: any_tap signal

### ISSUE THREAD

**Issue by rehhouari** [Federico-Ciuffardi/GodotTouchInputManager#32]
I'm working on a tapping game, and due to the fast pace it happens where the player can tap with multiple fingers, on different objects, currently using `single_tap` which wont register any of those taps which can be frustrating.

I found a way to get to get the position of multiple taps from `InputEventMultiScreenTap`  by looking into the `raw_event.centroid` function, and i can make a push request to add something like `InputEventMultiScreenTap.positions` array  with them if you'd want.
But more than that I think it could be helpful to have a signal that is emitted on either `single_tap` or `multi_tap`, with `positions` array property for cases such as mine.
I can also implement this.

thanks for the great plugin!

**Comment by Federico-Ciuffardi** [comment]
@rehhouari I'm sorry but I had to revert https://github.com/Federico-Ciuffardi/GodotTouchInputManager/pull/34 because I just realized that it was causing repeated events to be emitted to `_input` and also to the `any_gesture` signal.

Maybe you could try using `emit_signal` directly instead of `_emit`.

Although in my opinion it would be better to let GDTIM users handle this like this:
```
if event is InputEventSingleScreenTap:
#...
elif event is InputEventMultiScreenTap:
#...
```
and avoid making GDTIM more complex. Since otherwise we would be making a special case only for signals and taps.

If differentiating between single and multi custom input events is not really useful in general, I would prefer to evaluate merging them all, for example `InputEventSingleScreenTap` and `InputEventMultiScreenTap` into `InputEventScreenTap`, and let users decide to filter the `InputEventScreenTap` events with more than one finger if they would like to something similar to `InputEventSingleScreenTap`.

Let me know what you think.

**Comment by rehhouari** [comment]
Oh no problem since I didn't use anything beside `any_tap` so I didn't notice the issues

> If differentiating between single and multi custom input events is not really useful in general

if the library has been at use without anyone beside me having this use case before, then the current default is good.
if it's merged into one event, current users would have to make their `single_tap` code longer by checking for number of fingers which isn't worth it.

that said i also think it's better but it's a breaking change, if this was a new project it would have been unproblematic to do.

thanks for accepting the PR!
